language: r
r: 
  - 3.4.2
sudo: required
before_install:
- sudo mkdir -p /usr/lib/R/library
- echo 'R_LIBS=/usr/lib/R/library:/usr/lib/R/site-library/' > ~/.Renviron
- sudo chmod 2777 /usr/lib/R/library
- sudo add-apt-repository -y ppa:opencpu/jq
- sudo apt-get update
- sudo apt-get install libproj-dev libgdal-dev libv8-3.14-dev libprotobuf-dev protobuf-compiler libjq-dev 
install:
- R -e "0" --args --bootstrap-packrat
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

git:
  depth: 3

env:
  global:
    - secure: GITHUB_PAT

r_packages:
 - devtools
 - dplyr
 - ggplot2
 - futile.logger

install:
  - R -e "0" --args --bootstrap-packrat

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
